server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

#\u914D\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tian940603
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&amp;useUnicode=true

#\u81EA\u52A8\u5EFA\u8868\uFF0Cupdate\u8868\u793A\u4FEE\u6539
  jpa:
    hibernate:
      ddl-auto: update
#\u6253\u5370sql
      show-sql=true
  jackson:
    serialization:
      indent_output: true

# Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
  redis:
    database: 0
# Redis\u670D\u52A1\u5668\u5730\u5740
    host: 127.0.0.1
# Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    port: 6379
# Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    password: tian940603

#\u81EA\u5B9A\u4E49redis\u914D\u7F6E
myredis:
  host: localhost
  port: 6379
  password: tian940603
  timeout: 10
  pool-max-total: 1000
  pool-max-idle: 500
  pool-max-wait: 500


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#\u5E76\u53D1\u6D88\u8D39\u8005\u7684\u521D\u59CB\u5316\u503C
    listener:
      simple:
        concurrency: 10
#\u5E76\u53D1\u6D88\u8D39\u8005\u7684\u6700\u5927\u503C
        max-concurrency: 20
#\u6BCF\u4E2A\u6D88\u8D39\u8005\u6BCF\u6B21\u76D1\u542C\u65F6\u53EF\u62C9\u53D6\u7684\u6D88\u8D39\u4FE1\u606F\u6570\u91CF
        prefetch: 5

mq:
  env: local

log:
  user:
    queue:
      name: ${mq.env}.log.user.queue
    exchange:
      name: ${mq.env}.log.user.exchange
    routing:
      key:
        name: ${mq.env}.log.user.routing.key

